'use client'
import { Button,Dialog,DialogTrigger,Heading,Modal,ModalOverlay } from 'react-aria-components'
import { ConfirmAction } from '@/components/common/ConfirmAction'
import { createAvailability,deleteAvailability } from '../actions'
import type { AvailabilityItem } from '../repositories/availabilityRepository'
import { useActionState } from 'react'
import { initialActionState } from '@/lib/actionState'
import { SubmitButton } from '@/components/common/SubmitButton'
export function AvailabilityManager({slots}:{slots:AvailabilityItem[]}){const[state,formAction]=useActionState(createAvailability,initialActionState);return <><DialogTrigger><Button className="primary-action">Add Availability</Button><ModalOverlay className="modal-overlay" isDismissable><Modal className="availability-modal"><Dialog>{({close})=><><Heading slot="title">Add Availability</Heading><p>Create an open time for student requests.</p><form action={formAction} className="availability-form"><label>Date<input name="date" type="date" required/></label><label>Start<input name="startTime" type="time" required/></label><label>End<input name="endTime" type="time" required/></label><label>Mode<select name="mode" required><option value="IN_PERSON">In person</option><option value="ONLINE">Online</option></select></label><label>Location<input name="location" maxLength={160}/></label><label>Meeting link<input name="meetingLink" type="url"/></label><p className="form-message" role="alert">{state.error}</p><div className="dialog-actions"><Button type="button" onPress={close}>Cancel</Button><SubmitButton pendingLabel="Adding…">Add availability</SubmitButton></div></form></>}</Dialog></Modal></ModalOverlay></DialogTrigger><section className="slot-list" aria-label="Upcoming availability">{slots.length===0?<p className="empty-row">No upcoming availability.</p>:slots.map(slot=><article key={slot.id}><DialogTrigger><Button className="slot-detail-trigger"><time dateTime={slot.date}>{new Intl.DateTimeFormat('en-PH',{dateStyle:'medium'}).format(new Date(`${slot.date}T00:00:00`))}</time></Button><ModalOverlay className="modal-overlay" isDismissable><Modal className="confirm-modal"><Dialog><Heading slot="title">Availability details</Heading><dl className="detail-list"><dt>Date</dt><dd>{slot.date}</dd><dt>Time</dt><dd>{slot.start_time.slice(0,5)}–{slot.end_time.slice(0,5)}</dd><dt>Status</dt><dd>{slot.status}</dd><dt>Mode</dt><dd>{slot.mode==='IN_PERSON'?slot.location:'Online'}</dd></dl></Dialog></Modal></ModalOverlay></DialogTrigger><strong>{slot.start_time.slice(0,5)}–{slot.end_time.slice(0,5)}</strong><span className="status-badge">{slot.status}</span><span>{slot.mode==='IN_PERSON'?slot.location:'Online'}</span>{slot.status==='OPEN'&&<ConfirmAction label="Remove" title="Remove availability?" description="Students will no longer be able to request this time." fields={{slotId:slot.id}} submitAction={deleteAvailability} variant="danger"/>}</article>)}</section></>}
